"use strict";

const DEFAULT_TRUST_POLICIES = [
  {
    id: "trust_activity_submitted",
    name: "首次开放发起行为",
    eventType: "activity.submitted",
    enabled: true,
    order: 10,
    description: "真实用户愿意把活动写完整并提交，本身就是轻微正向社区行为。",
    conditionMode: "all",
    conditions: [{ field: "event.payload.intent", op: "eq", value: "submit" }],
    effect: { trustDelta: 1 },
  },
  {
    id: "trust_confidence_95_plus",
    name: "活动置信度 >= 95",
    eventType: "activity.confidence.evaluated",
    enabled: true,
    order: 20,
    description: "活动置信度很高时，给匿名身份较明显的正向积累。",
    conditionMode: "all",
    conditions: [{ field: "event.payload.confidenceScore", op: "gte", value: 95 }],
    effect: { trustDelta: 3 },
  },
  {
    id: "trust_confidence_90_94",
    name: "活动置信度 90-94",
    eventType: "activity.confidence.evaluated",
    enabled: true,
    order: 30,
    description: "活动置信度较高时，给匿名身份正向积累。",
    conditionMode: "all",
    conditions: [{ field: "event.payload.confidenceScore", op: "between", value: [90, 94] }],
    effect: { trustDelta: 2 },
  },
  {
    id: "trust_confidence_80_89",
    name: "活动置信度 80-89",
    eventType: "activity.confidence.evaluated",
    enabled: true,
    order: 40,
    description: "活动置信度稳定时，给匿名身份轻微正向积累。",
    conditionMode: "all",
    conditions: [{ field: "event.payload.confidenceScore", op: "between", value: [80, 89] }],
    effect: { trustDelta: 1 },
  },
  {
    id: "trust_confidence_40_59",
    name: "活动置信度 40-59",
    eventType: "activity.confidence.evaluated",
    enabled: true,
    order: 50,
    description: "活动置信度偏低时，逐步降低匿名身份信任，而不是一票否决。",
    conditionMode: "all",
    conditions: [{ field: "event.payload.confidenceScore", op: "between", value: [40, 59] }],
    effect: { trustDelta: -2 },
  },
  {
    id: "trust_confidence_below_40",
    name: "活动置信度 < 40",
    eventType: "activity.confidence.evaluated",
    enabled: true,
    order: 60,
    description: "活动置信度很低时，明显降低匿名身份信任并进入观察。",
    conditionMode: "all",
    conditions: [{ field: "event.payload.confidenceScore", op: "lt", value: 40 }],
    effect: { trustDelta: -5 },
  },
  {
    id: "trust_activity_published",
    name: "活动成功发布",
    eventType: "activity.published",
    enabled: true,
    order: 70,
    description: "活动通过策略或兜底复核后成功发布，给组织者正向积累。",
    conditionMode: "all",
    conditions: [],
    effect: { trustDelta: 2 },
  },
  {
    id: "trust_registration_milestone_10",
    name: "活动报名达到 10 人",
    eventType: "activity.registration.milestone",
    enabled: true,
    order: 80,
    description: "真实报名是社区回应；每达到一个报名里程碑，给发起者轻微正向积累。",
    conditionMode: "all",
    conditions: [{ field: "event.payload.milestone", op: "gte", value: 10 }],
    effect: { trustDelta: 1 },
  },
  {
    id: "trust_report_confirmed",
    name: "社区举报成立",
    eventType: "community.report.confirmed",
    enabled: true,
    order: 90,
    description: "社区反馈达到阈值且再次分析为高风险时，降低发起者信任。",
    conditionMode: "all",
    conditions: [],
    effect: { trustDelta: -15 },
  },
];

const DEFAULT_COMMUNITY_BADGES = [
  {
    id: "badge_new_friend",
    name: "新朋友",
    description: "刚开始在有空发起和参与的人。",
    icon: "spark",
    color: "#6f7f63",
    type: "identity",
    enabled: true,
    order: 10,
    rule: {
      mode: "all",
      conditions: [{ field: "profile.communityTrust", op: "gte", value: 0 }],
    },
  },
  {
    id: "badge_trusted_host",
    name: "可信发起人",
    description: "连续留下较清楚、较稳定的活动记录。",
    icon: "check",
    color: "#256f5b",
    type: "achievement",
    enabled: true,
    order: 20,
    rule: {
      mode: "all",
      conditions: [
        { field: "profile.communityTrust", op: "gte", value: 70 },
        { field: "profile.activityCount", op: "gte", value: 3 },
      ],
    },
  },
  {
    id: "badge_community_partner",
    name: "社区伙伴",
    description: "长期保持高信任且没有成立举报记录的伙伴。",
    icon: "leaf",
    color: "#1f5f74",
    type: "identity",
    enabled: true,
    order: 30,
    rule: {
      mode: "all",
      conditions: [
        { field: "profile.communityTrust", op: "gte", value: 80 },
        { field: "profile.reportConfirmedCount", op: "lte", value: 0 },
      ],
    },
  },
  {
    id: "badge_consistent_organizer",
    name: "持续组织者",
    description: "累计发起 10 场以上活动。",
    icon: "calendar",
    color: "#9a4d35",
    type: "achievement",
    enabled: true,
    order: 40,
    rule: {
      mode: "all",
      conditions: [{ field: "profile.activityCount", op: "gte", value: 10 }],
    },
  },
];

const DEFAULT_BADGE_POLICIES = [
  {
    id: "display_badge_new_friend",
    badgeId: "badge_new_friend",
    enabled: true,
    publicVisible: false,
    displayLocations: {
      activityCard: false,
      activityDetail: false,
      initiatorProfile: false,
      registrationList: false,
      adminOnly: true,
    },
    showIcon: true,
    showName: true,
    tooltip: "后台可见的新身份标记。",
    order: 10,
  },
  {
    id: "display_badge_trusted_host",
    badgeId: "badge_trusted_host",
    enabled: true,
    publicVisible: true,
    displayLocations: {
      activityCard: true,
      activityDetail: true,
      initiatorProfile: true,
      registrationList: false,
      adminOnly: false,
    },
    showIcon: true,
    showName: true,
    tooltip: "这个发起者有较稳定的真实活动记录。",
    order: 20,
  },
  {
    id: "display_badge_community_partner",
    badgeId: "badge_community_partner",
    enabled: true,
    publicVisible: true,
    displayLocations: {
      activityCard: true,
      activityDetail: true,
      initiatorProfile: true,
      registrationList: false,
      adminOnly: false,
    },
    showIcon: true,
    showName: true,
    tooltip: "长期保持高信任的社区伙伴。",
    order: 30,
  },
  {
    id: "display_badge_consistent_organizer",
    badgeId: "badge_consistent_organizer",
    enabled: true,
    publicVisible: true,
    displayLocations: {
      activityCard: false,
      activityDetail: true,
      initiatorProfile: true,
      registrationList: false,
      adminOnly: false,
    },
    showIcon: true,
    showName: true,
    tooltip: "持续组织活动的发起者。",
    order: 40,
  },
];

module.exports = {
  DEFAULT_BADGE_POLICIES,
  DEFAULT_COMMUNITY_BADGES,
  DEFAULT_TRUST_POLICIES,
};
