"use strict";

const DEFAULT_SAFETY_CONFIG = {
  version: 1,
  turnstile: {
    enabled: false,
    siteKey: "",
    bypassLocal: true,
    requiredBelowTrust: 35,
  },
  rateLimit: {
    publishMinuteWindowMs: 60 * 1000,
    publishMinuteMax: 2,
    publishDayWindowMs: 24 * 60 * 60 * 1000,
    publishDayMax: 5,
    draftMinuteMax: 8,
    uploadMinuteMax: 12,
    reportDayMax: 12,
    highTrustBonus: 2,
    lowTrustPenalty: 1,
  },
  ruleEngine: {
    baseRiskScore: 8,
    aiMediumRiskMin: 30,
    aiMediumRiskMax: 70,
  },
  trust: {
    initial: 50,
    min: 0,
    max: 100,
    lowTrustThreshold: 25,
    highTrustThreshold: 75,
    deltas: {
      activitySubmitted: 1,
      activityPublished: 3,
      lowRiskActivity: 2,
      mediumRiskActivity: -3,
      highRiskActivity: -8,
      communityReportConfirmed: -10,
      communityReportSubmitted: 0,
      registrationReceived: 1,
    },
  },
  report: {
    threshold: 3,
    warningThreshold: 2,
    highRiskThreshold: 70,
    substantiatedMinRisk: 60,
    autoHideThreshold: 90,
    hideOnHighRisk: true,
    requireAdminReviewOnSubstantiated: true,
  },
  policy: {
    publishDirectMaxRisk: 29,
    publishWithNoticeMaxRisk: 59,
    fallbackReviewMinRisk: 60,
    rejectMinRisk: 96,
    highRiskAction: "review",
    mediumRiskNotice: true,
    reviewNeedsCollaborator: false,
    aiRiskInfluence: 0.5,
    aiMaxRiskDecrease: 0,
    aiMaxRiskIncrease: 45,
    aiUnavailableAction: "review",
    aiUnavailableReviewMinRisk: 30,
    aiUnavailableReviewWhenAiExpected: true,
    clearSignalConfidence: 0.72,
    suspectedSignalConfidence: 0.45,
    clearAdvertisementMinRisk: 75,
    clearSpamMinRisk: 75,
    aiSignalRiskFloors: {
      suspectedAdvertisement: 40,
      clearAdvertisement: 75,
      clearSpam: 80,
      scam: 92,
      illegal: 90,
      adult: 90,
      political: 95,
    },
  },
  recommendation: {
    baseWeight: 100,
    mediumRiskPenalty: 30,
    highRiskPenalty: 70,
    highTrustBonus: 15,
  },
};

const DEFAULT_SAFETY_RULES = [
  {
    id: "sensitive_terms",
    name: "违法违规敏感词检测",
    type: "sensitive_terms",
    enabled: true,
    weight: 28,
    description: "命中违法、诈骗、灰产等高风险词汇时增加风险分。",
    params: {
      terms: ["诈骗", "洗钱", "博彩", "代考", "裸聊", "约炮", "办证", "黑产", "返利盘", "资金盘"],
    },
  },
  {
    id: "regulated_sensitive_terms",
    name: "重点风险词检测",
    type: "sensitive_terms",
    enabled: true,
    weight: 38,
    description: "命中赌场、发票、投资、成人等明显不适合开放活动发布的高风险词汇。",
    params: {
      terms: ["澳门赌场", "赌场", "发票", "代开发票", "投资", "理财", "成人", "成人视频", "成人服务", "色情", "贷款", "套现", "返现"],
      perHitWeight: 8,
      maxExtraWeight: 32,
    },
  },
  {
    id: "url_density",
    name: "URL 检测",
    type: "url_density",
    enabled: true,
    weight: 14,
    description: "正文中包含外链或外链密度过高时增加风险分。",
    params: { allowedDomains: [], highDensity: 3 },
  },
  {
    id: "html_tag_filter",
    name: "HTML 标签过滤",
    type: "html_tag_filter",
    enabled: true,
    weight: 12,
    description: "检测富文本中不在白名单内的 HTML 标签。",
    params: { allowedTags: ["p", "h1", "h2", "h3", "ul", "ol", "li", "blockquote", "strong", "b", "em", "i", "u", "a", "img", "br", "hr"] },
  },
  {
    id: "script_injection",
    name: "Script 注入过滤",
    type: "script_injection",
    enabled: true,
    weight: 40,
    description: "检测 script、事件属性、javascript: 等脚本注入痕迹。",
    params: {},
  },
  {
    id: "markdown_dangerous",
    name: "Markdown 危险语法过滤",
    type: "markdown_dangerous",
    enabled: true,
    weight: 16,
    description: "检测 Markdown 中的 javascript 链接、HTML iframe/object 等危险片段。",
    params: {},
  },
  {
    id: "unicode_confusable",
    name: "Unicode 混淆字符标准化",
    type: "unicode_confusable",
    enabled: true,
    weight: 10,
    description: "检测大量不可见字符、全角混淆字符和组合字符。",
    params: { maxSuspiciousChars: 8 },
  },
  {
    id: "emoji_ratio",
    name: "Emoji 比例检测",
    type: "emoji_ratio",
    enabled: true,
    weight: 8,
    description: "Emoji 比例过高时增加广告或垃圾内容风险。",
    params: { maxRatio: 0.18 },
  },
  {
    id: "repeated_chars",
    name: "重复字符检测",
    type: "repeated_chars",
    enabled: true,
    weight: 10,
    description: "检测夸张重复字符、符号刷屏和标题党格式。",
    params: { repeatLength: 6 },
  },
  {
    id: "long_text",
    name: "超长文本检测",
    type: "long_text",
    enabled: true,
    weight: 10,
    description: "正文长度异常接近上限时增加风险分。",
    params: { maxSoftLength: 12000 },
  },
  {
    id: "duplicate_content",
    name: "大量重复内容检测",
    type: "duplicate_content",
    enabled: true,
    weight: 14,
    description: "检测重复段落或重复词块过多的内容。",
    params: { maxDuplicateRatio: 0.35 },
  },
  {
    id: "abnormal_format",
    name: "异常格式检测",
    type: "abnormal_format",
    enabled: true,
    weight: 12,
    description: "检测全大写、过多符号、联系方式堆砌等异常格式。",
    params: { maxSymbolRatio: 0.28 },
  },
  {
    id: "activity_completeness",
    name: "真实活动完整度",
    type: "activity_completeness",
    enabled: true,
    weight: -12,
    description: "时间、地点、发起人、流程描述越完整，活动置信度越高。",
    params: {},
  },
];

const DEFAULT_AI_SETTINGS = {
  enabled: false,
  provider: "openai-compatible",
  baseUrl: "",
  model: "",
  apiKeyEncrypted: "",
  apiKeyUpdatedAt: "",
  requestTimeoutMs: 15000,
  temperature: 0.2,
  maxTokens: 1200,
  retryCount: 1,
  cacheTtlSeconds: 24 * 60 * 60,
  promptVersion: "activity-default-v1",
  callStrategy: {
    allContent: false,
    lowConfidenceOnly: true,
    ruleConfidenceMax: 70,
    firstActivitiesAlways: true,
    firstActivityCount: 3,
    mediumRiskOnly: false,
    lowTrustOnly: false,
    randomSampleRate: 0,
    reportedContent: true,
    manualReanalysis: true,
    mediumRiskMin: 30,
    mediumRiskMax: 70,
    lowTrustThreshold: 35,
  },
  capabilities: {
    riskAnalysis: true,
    activityClassification: true,
    tagGeneration: true,
    summary: true,
    timeExtraction: true,
    locationExtraction: true,
    titleSuggestion: true,
    seoDescription: false,
    recommendationReason: false,
  },
  systemPrompt: "",
};

const DEFAULT_AI_PROMPTS = [
  {
    id: "prompt_activity_default_v1",
    type: "activity",
    version: "activity-default-v1",
    name: "活动分析默认 Prompt",
    active: true,
    systemPrompt: [
      "你是有空客厅 Community OS 的社区观察员和内容分析引擎。",
      "你的职责不是审核、删除或封禁，而是理解活动内容，输出客观、结构化、可解释的分析报告。",
      "请只输出 JSON，不要输出 Markdown。",
    ].join("\n"),
    userPrompt: [
      "请分析以下社区活动内容，判断它是否像真实活动、是否有广告营销或诈骗风险，并提取结构化信息。",
      "如果内容涉及政治敏感，即使只是疑似，也请将 containsPolitical 设为 true，并在 riskReason 中解释。",
      "如果内容有营销倾向，请区分 advertisementLevel：suspected 表示轻微或疑似营销，clear 表示明确营销、引流、招商、代理、返利或销售。",
      "输出字段必须符合系统提供的 JSON Schema。风险分数越高代表越需要社区谨慎判断。",
    ].join("\n"),
  },
];

module.exports = {
  DEFAULT_AI_PROMPTS,
  DEFAULT_AI_SETTINGS,
  DEFAULT_SAFETY_CONFIG,
  DEFAULT_SAFETY_RULES,
};
